config/routes.rb
PetGestor::Application.routes.draw do
  devise_for :usuarios

  root :to => "managements#index"

  resources :atividades
  resources :usuarios
end

app/models/atividade.rb
class Atividade < ActiveRecord::Base
  has_many :etapa_atividades
  has_many :realizacaos
  has_and_belongs_to_many :usuarios
end

app/models/etapa_atividade.rb
class EtapaAtividade < ActiveRecord::Base
  belongs_to :atividade
end

app/models/etapa_realizacao.rb
class EtapaRealizacao < ActiveRecord::Base
  belongs_to :realizacao
end

app/models/realizacao.rb
class Realizacao < ActiveRecord::Base
  belongs_to :atividade
  has_many :etapa_realizacaos
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :cpf, :nome, :data_aniversario, :telefone_casa, :telefone_celular, :ingresso_faculdade, :ingresso_pet, :ativo
  # attr_accessible :title, :body

  validates_presence_of :nome, :cpf, :email
  validates_uniqueness_of :email

  has_and_belongs_to_many :atividades
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_usuario!
  protect_from_forgery
end

app/controllers/atividades_controller.rb
class AtividadesController < ApplicationController
  
  def index
  end

  def show
  end

end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController

  # before_filter :login_required

  def index
    
  end

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  
  def index
    @usuarios = Usuario.find :all 
  end
  
  def show
    @usuario = Usuario.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atividades_helper.rb
module AtividadesHelper
end

app/helpers/managements_helper.rb
module ManagementsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/atividades/index.html.erb
<h1>Atividades#index</h1>
<p>Find me in app/views/atividades/index.html.erb</p>

app/views/atividades/show.html.erb
<h1>Atividades#show</h1>
<p>Find me in app/views/atividades/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
    <title>PET Gestor</title>
    <%= stylesheet_link_tag "reset", "normalize", "style", "form", "jquery-ui-1.8.16.custom" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
  </head>

  <body>
    <div id="container">
      <div id="header">
        <a href="/"><img src="/images/logoP.png"/></a>
      </div>

      <div id="content">
        <div id="content-bg"></div>
        <%= yield %>
      </div>

      <a href="#" class="btnSair">Sair</a>
    </div>
  </body>
</html>

app/views/managements/index.html.erb
<p>Managements</p>

app/views/usuarios/index.html.erb
<style>
  label {
    display: block;
    margin: 1em;
  }
</style>

<form method="post" action="">
  <div>
    <label>Buscar Petiano: <input type="text" name="buscarpetiano"/> <input type="submit" value="Buscar"/></label>
    <label><input type="checkbox"/>Exibir Inativos </label>
    <table>
      <tr>
        <th>Login</th>
        <th>Nome</th>
        <th>Email</th>
        <th>Ativo</th>
      </tr>
      <% for usuario in @usuarios %>
        <tr>
          <td><%= link_to usuario.login, usuario_path(usuario)  %></td>
          <td><%= usuario.nome %></td>
          <td><%= usuario.email  %></td>
          <% if usuario.ativo %>
            <td>Sim</td>
          <% else %>
            <td>Não</td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>
</form>

app/views/usuarios/show.html.erb
Nome:<%= @usuario.nome %>